package com.ddliu.dao;

import com.ddliu.entity.po.TPxxRbxq;

import java.util.List;

public interface TPxxRbxqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_RBXQ
     *
     * @mbggenerated
     */
    int insert(TPxxRbxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_RBXQ
     *
     * @mbggenerated
     */
    List<TPxxRbxq> selectAll();
}