package com.ddliu.dao;

import com.ddliu.entity.po.TPxxDppf;

import java.util.List;

public interface TPxxDppfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_DPPF
     *
     * @mbggenerated
     */
    int insert(TPxxDppf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_DPPF
     *
     * @mbggenerated
     */
    List<TPxxDppf> selectAll();
}