package com.ddliu.dao;

import com.ddliu.entity.po.TPxxCd;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TPxxCdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_CD
     *
     * @mbggenerated
     */
    int insert(TPxxCd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_CD
     *
     * @mbggenerated
     */
    List<TPxxCd> selectAll();

    String selectMyCds();
}