package com.ddliu.dao;

import com.ddliu.entity.po.TPxxFwsm;

import java.util.List;

public interface TPxxFwsmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FWSM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FWSM
     *
     * @mbggenerated
     */
    int insert(TPxxFwsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FWSM
     *
     * @mbggenerated
     */
    TPxxFwsm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FWSM
     *
     * @mbggenerated
     */
    List<TPxxFwsm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FWSM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPxxFwsm record);
}