package com.ddliu.dao;

import com.ddliu.entity.po.TPxxGood;

import java.util.List;

public interface TPxxGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_GOOD
     *
     * @mbggenerated
     */
    int insert(TPxxGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_GOOD
     *
     * @mbggenerated
     */
    List<TPxxGood> selectAll();
}