package com.ddliu.dao;

import com.ddliu.entity.po.TPxxFile;

import java.util.List;

public interface TPxxFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FILE
     *
     * @mbggenerated
     */
    int insert(TPxxFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FILE
     *
     * @mbggenerated
     */
    List<TPxxFile> selectAll();
}