package com.ddliu.dao;

import com.ddliu.entity.po.TPxxSppj;

import java.util.List;

public interface TPxxSppjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    int insert(TPxxSppj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    TPxxSppj selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    List<TPxxSppj> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPxxSppj record);
}