package com.ddliu.entity.po;

import java.io.Serializable;

public class TPxxCd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_CD.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_CD.cd_name
     *
     * @mbggenerated
     */
    private String cdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_CD.cd_icon
     *
     * @mbggenerated
     */
    private String cdIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PXX_CD
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_CD.id
     *
     * @return the value of T_PXX_CD.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_CD.id
     *
     * @param id the value for T_PXX_CD.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_CD.cd_name
     *
     * @return the value of T_PXX_CD.cd_name
     *
     * @mbggenerated
     */
    public String getCdName() {
        return cdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_CD.cd_name
     *
     * @param cdName the value for T_PXX_CD.cd_name
     *
     * @mbggenerated
     */
    public void setCdName(String cdName) {
        this.cdName = cdName == null ? null : cdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_CD.cd_icon
     *
     * @return the value of T_PXX_CD.cd_icon
     *
     * @mbggenerated
     */
    public String getCdIcon() {
        return cdIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_CD.cd_icon
     *
     * @param cdIcon the value for T_PXX_CD.cd_icon
     *
     * @mbggenerated
     */
    public void setCdIcon(String cdIcon) {
        this.cdIcon = cdIcon == null ? null : cdIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_CD
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cdName=").append(cdName);
        sb.append(", cdIcon=").append(cdIcon);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}