package com.ddliu.entity.po;

import java.io.Serializable;

public class TPxxFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.PHASE_ID
     *
     * @mbggenerated
     */
    private String phaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.SIZE
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.SOURCE
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_FILE.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PXX_FILE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.id
     *
     * @return the value of T_PXX_FILE.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.id
     *
     * @param id the value for T_PXX_FILE.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.PHASE_ID
     *
     * @return the value of T_PXX_FILE.PHASE_ID
     *
     * @mbggenerated
     */
    public String getPhaseId() {
        return phaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.PHASE_ID
     *
     * @param phaseId the value for T_PXX_FILE.PHASE_ID
     *
     * @mbggenerated
     */
    public void setPhaseId(String phaseId) {
        this.phaseId = phaseId == null ? null : phaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.NAME
     *
     * @return the value of T_PXX_FILE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.NAME
     *
     * @param name the value for T_PXX_FILE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.SIZE
     *
     * @return the value of T_PXX_FILE.SIZE
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.SIZE
     *
     * @param size the value for T_PXX_FILE.SIZE
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.TYPE
     *
     * @return the value of T_PXX_FILE.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.TYPE
     *
     * @param type the value for T_PXX_FILE.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.PATH
     *
     * @return the value of T_PXX_FILE.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.PATH
     *
     * @param path the value for T_PXX_FILE.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.SOURCE
     *
     * @return the value of T_PXX_FILE.SOURCE
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.SOURCE
     *
     * @param source the value for T_PXX_FILE.SOURCE
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_FILE.CREATE_TIME
     *
     * @return the value of T_PXX_FILE.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_FILE.CREATE_TIME
     *
     * @param createTime the value for T_PXX_FILE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_FILE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phaseId=").append(phaseId);
        sb.append(", name=").append(name);
        sb.append(", size=").append(size);
        sb.append(", type=").append(type);
        sb.append(", path=").append(path);
        sb.append(", source=").append(source);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}