package com.ddliu.entity.po;

import java.io.Serializable;

public class TPxxSppj implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_SPPJ.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_SPPJ.good_id
     *
     * @mbggenerated
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_SPPJ.msxf
     *
     * @mbggenerated
     */
    private String msxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_SPPJ.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_SPPJ.dppf_id
     *
     * @mbggenerated
     */
    private String dppfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_SPPJ.id
     *
     * @return the value of T_PXX_SPPJ.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_SPPJ.id
     *
     * @param id the value for T_PXX_SPPJ.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_SPPJ.good_id
     *
     * @return the value of T_PXX_SPPJ.good_id
     *
     * @mbggenerated
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_SPPJ.good_id
     *
     * @param goodId the value for T_PXX_SPPJ.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_SPPJ.msxf
     *
     * @return the value of T_PXX_SPPJ.msxf
     *
     * @mbggenerated
     */
    public String getMsxf() {
        return msxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_SPPJ.msxf
     *
     * @param msxf the value for T_PXX_SPPJ.msxf
     *
     * @mbggenerated
     */
    public void setMsxf(String msxf) {
        this.msxf = msxf == null ? null : msxf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_SPPJ.content
     *
     * @return the value of T_PXX_SPPJ.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_SPPJ.content
     *
     * @param content the value for T_PXX_SPPJ.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_SPPJ.dppf_id
     *
     * @return the value of T_PXX_SPPJ.dppf_id
     *
     * @mbggenerated
     */
    public String getDppfId() {
        return dppfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_SPPJ.dppf_id
     *
     * @param dppfId the value for T_PXX_SPPJ.dppf_id
     *
     * @mbggenerated
     */
    public void setDppfId(String dppfId) {
        this.dppfId = dppfId == null ? null : dppfId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_SPPJ
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodId=").append(goodId);
        sb.append(", msxf=").append(msxf);
        sb.append(", content=").append(content);
        sb.append(", dppfId=").append(dppfId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}