package com.ddliu.entity.po;

import java.io.Serializable;

public class TPxxDppf implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_DPPF.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_DPPF.msxf
     *
     * @mbggenerated
     */
    private String msxf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PXX_DPPF.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PXX_DPPF
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_DPPF.id
     *
     * @return the value of T_PXX_DPPF.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_DPPF.id
     *
     * @param id the value for T_PXX_DPPF.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_DPPF.msxf
     *
     * @return the value of T_PXX_DPPF.msxf
     *
     * @mbggenerated
     */
    public String getMsxf() {
        return msxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_DPPF.msxf
     *
     * @param msxf the value for T_PXX_DPPF.msxf
     *
     * @mbggenerated
     */
    public void setMsxf(String msxf) {
        this.msxf = msxf == null ? null : msxf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PXX_DPPF.content
     *
     * @return the value of T_PXX_DPPF.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PXX_DPPF.content
     *
     * @param content the value for T_PXX_DPPF.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PXX_DPPF
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", msxf=").append(msxf);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}